debug: false
management.endpoints.web.exposure.include: "*"



logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: psm
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb #h2 테스트 db로 활용하기 위해선 다음을 꼭 기억하고 작성해야한다. http://localhost:8080/h2-console
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  h2.console.enabled: false
  sql.init.mode: always
  data.rest:
      base-path: /api
      detection-strategy: annotated #annotaion에 지정한 레포지토리만 api로 노출시키는 옵션
  thymeleaf3.decoupled-logic: true


--- #해당 분기점을 기준으로 설정을 분리하고 분리한 설정 값을 의도에 맞게 배치하여 사용 가능함.
#spring:
#  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none #auto값을 사용하지 않고 activeprofile에 지정한 db 옵션으로 사용하겠다는 명시 default는 any / 전역으로도 활용 가능

